const DEFAULT_PROJECT_IMAGE = "/projects/default-project.svg";

const PH_MAILER_IMAGE = "/evidence/ph-mailer-statistics.webp";
const BOOTCAMP_IMAGE = "/evidence/bootcamp-statistics.webp";
const SPEAKSAIL_IMAGE = "/projects/speaksail-com.webp";
const SKILL_MAPPER_IMAGE = "/projects/skill-mapper-programming-hero.webp";

export const projects = [
    {
        _id: "featured-1",
        name: "PH Mailer",
        title: "PH Mailer",
        subtitle: "Centralized Email Platform",
        time: "Production",
        shortDescription:
            "Production email platform: forked Plunk, custom BullMQ worker + Redis queue, delivery via AWS SES",
        metrics: [
            "197K+ emails sent (7-day window)",
            "5 internal product teams",
            "~50–60% lower send cost vs Mailgun",
        ],
        priority: 105,
        category: "Backend / Platform",
        status: "Production",
        tier: "featured",
        proprietary: true,
        caseStudyLink: "/projects/ph-mailer",
        description: [
            "Centralized email platform forked from open-source Plunk, extended with a custom BullMQ worker and Redis-backed queue, with delivery routed through AWS SES. The challenge was designing a shared service that multiple internal products could adopt without each team losing control over their email templates and delivery tracking.",
            "Own production maintenance, feature development, and upstream synchronization with Plunk's API. Responsibilities include delivery monitoring, bounce handling, and coordinating template changes across teams with different release schedules.",
            "Forking Plunk was chosen over self-hosted SMTP (Postfix) and direct AWS SES: Plunk provides the template/analytics layer out of the box, while custom BullMQ workers add queue-based async delivery and SES handles outbound delivery. SES alone was rejected due to template management overhead for a small team.",
        ],
        highlights: [
            "Production platform ownership maintenance, monitoring, features",
            "Forked Plunk + custom BullMQ worker queue, delivery via AWS SES",
            "Cross-team coordination for shared internal service",
        ],
        image: PH_MAILER_IMAGE,
        tools: ["Node.js", "TypeScript", "Plunk", "BullMQ", "Redis", "AWS SES", "Docker"],
        stack: ["Node.js", "TypeScript", "Plunk", "BullMQ", "Redis", "AWS SES", "Docker"],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "",
        links: { github: null, live: null },
    },
    {
        _id: "featured-2",
        title: "ph-auth-service",
        name: "PH Auth Service",
        subtitle: "Multi-Tenant Auth Platform",
        time: "2024 – Present",
        shortDescription: "Multi-tenant auth platform on ZITADEL with custom Go product layer",
        metrics: [
            "Multi-tenant isolation for 4 products",
            "7-layer defense-in-depth",
            "2 engineers coordinated",
        ],
        priority: 104,
        category: "Backend / Security",
        status: "Complete awaiting production release",
        tier: "past-work",
        proprietary: true,
        caseStudyLink: "/projects/ph-auth-service",
        description: [
            "Multi-tenant authentication platform using ZITADEL as the OIDC provider, with a custom Go product layer handling tenant-specific business logic. ZITADEL was chosen over Keycloak (operational complexity for a small team) and Auth0 (cost at multi-tenant scale) for its OIDC compliance and self-hosting flexibility.",
            "The custom Go layer handles SSR UI rendering, per-tenant configuration, and security controls that ZITADEL doesn't expose through its OIDC interface: MFA enrollment flows, per-user device-limit enforcement, CSP nonce injection, rate limiting, ReCAPTCHA integration, and CSRF protection.",
            "Coordinated implementation and reviewed work for two mid-level engineers. Collaborative architecture decisions under Senior SWE authority; I owned the Go layer design and integration logic.",
        ],
        highlights: [
            "Hybrid auth: ZITADEL OIDC + custom Go product layer",
            "MFA, device limits, rate limiting, CSP, CSRF hardening",
            "Coordinated two engineers; collaborative architecture",
        ],
        image: DEFAULT_PROJECT_IMAGE,
        tools: ["Go", "PostgreSQL", "ZITADEL", "OIDC", "OAuth2"],
        stack: ["Go", "PostgreSQL", "ZITADEL", "OIDC", "OAuth2"],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "",
        links: { github: null, live: null },
    },
    {
        _id: "featured-3",
        name: "PH Bootcamp Platform",
        title: "PH Bootcamp Platform",
        subtitle: "Full-Stack LMS with DRM, Payments & QR",
        time: "Production",
        shortDescription:
            "Full-stack LMS with DRM video, bKash payments, QR attendance, and WhatsApp group management",
        metrics: ["13,820+ total leads", "898+ active users", "85 automated tests"],
        priority: 103,
        category: "Backend / Platform",
        status: "Production",
        tier: "featured",
        proprietary: false,
        caseStudyLink: "/projects/ph-bootcamp",
        description: [
            "Full-stack learning management system handling course delivery, event registration with bKash payments, DRM-protected video streaming, QR code attendance tracking, WhatsApp group management, and bootcamp lead capture across 13,820+ leads.",
            "Backend: Express.js + TypeScript with MongoDB, Redis caching (13 domain-specific adapters), ABAC authorization (5 roles, 13 resource types), bKash tokenized checkout with idempotency, DRM video delivery with IP restrictions, and an append-only activity audit log with secret auto-redaction.",
            "Frontend: React 19 + TanStack Router + Zustand + shadcn/ui with MSW-based test infrastructure (50 tests). Strict 3-layer architecture: Service → Hook → Component. Cookie-based SSO with external auth service.",
        ],
        highlights: [
            "Full-stack LMS: courses, events, DRM video, bKash payments, QR codes, WhatsApp groups",
            "ABAC authorization with 5 roles and 13 resource types",
            "85 automated tests (35 Vitest backend + 50 Vitest frontend)",
        ],
        image: BOOTCAMP_IMAGE,
        tools: [
            "TypeScript",
            "Node.js",
            "Express",
            "MongoDB",
            "Redis",
            "bKash",
            "Docker",
            "Vitest",
        ],
        stack: [
            "TypeScript",
            "Node.js",
            "Express",
            "MongoDB",
            "Redis",
            "bKash",
            "Docker",
            "Vitest",
        ],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "https://bootcamp.programming-hero.com",
        links: { github: null, live: "https://bootcamp.programming-hero.com" },
    },
    {
        _id: "featured-4",
        name: "SpeakSail / Enlightall",
        title: "SpeakSail / Enlightall",
        subtitle: "Language Learning Marketplace",
        time: "Freelance Client | Aug 2022 – Aug 2024",
        shortDescription:
            "Language-learning marketplace with live video tutoring, real-time messaging, and multi-gateway payments",
        metrics: ["27 database models", "90+ API routes", "7 user roles, 2 languages"],
        priority: 104,
        category: "Full Stack / Marketplace",
        status: "Production",
        tier: "featured",
        proprietary: false,
        caseStudyLink: "/projects/speaksail",
        description: [
            "Full-stack language-learning marketplace serving real students with instructor-led live lessons via Whereby API, Socket.IO real-time messaging, and multi-gateway payment processing (Stripe USD, Iyzipay TRY, Paymax). Built as a Next.js 14 monolith with 90+ API routes, 27 Mongoose models, and 7 user roles.",
            "Architected Firebase Auth + JWT hybrid authentication: Firebase handles identity (email/password + Google OAuth), JWT (jose) handles API authorization. Dual real-time notification system: Socket.IO for in-app messaging and Firebase Cloud Messaging for push notifications.",
            "Now evolving into SpeakSail. A complete rewrite using Laravel 11 backend with Filament admin panel and TanStack Start (React 19) frontend, adding AI-powered chat via Anthropic SDK. The rewrite decouples the monolith into a proper API backend + SPA frontend.",
        ],
        highlights: [
            "Live in production with real students (speaksail.com)",
            "Socket.IO + FCM dual notification system",
            "Evolution: Next.js monolith → Laravel + TanStack Start rewrite",
        ],
        image: SPEAKSAIL_IMAGE,
        tools: [
            "Next.js 14",
            "TypeScript",
            "MongoDB",
            "Firebase",
            "Socket.IO",
            "Stripe",
            "Laravel 11",
            "TanStack Start",
        ],
        stack: [
            "Next.js 14",
            "TypeScript",
            "MongoDB",
            "Firebase",
            "Socket.IO",
            "Stripe",
            "Laravel 11",
            "TanStack Start",
        ],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "https://speaksail.com",
        links: { github: null, live: "https://speaksail.com" },
    },
    {
        _id: "ph-payment-service",
        name: "Payment Service",
        title: "Payment Service",
        subtitle: "Centralized Payment Platform",
        time: "2024 – Present",
        shortDescription: "Centralized multi-gateway payment service for education products",
        metrics: [
            "3 gateways unified",
            "OpenAPI-generated Go server",
            "Polyglot persistence (3 databases)",
        ],
        priority: 94,
        category: "Backend / Payments",
        status: "In development",
        tier: "past-work",
        proprietary: true,
        caseStudyLink: "/projects/payment-service",
        description: [
            "Centralized payment service abstracting multiple payment gateways behind a unified API with an adapter pattern. Supports Stripe, bKash, and SSLCommerz with webhook processing, refund management, and transaction analytics.",
            "Built with OpenAPI specification and Go code generation for type-safe API contracts. Uses PostgreSQL for transaction records, a columnar database for analytics queries, and Redis for gateway token caching.",
        ],
        highlights: [
            "Multi-gateway adapter pattern for payment abstraction",
            "OpenAPI-generated server with type-safe contracts",
            "Polyglot persistence for transaction, analytics, and cache",
        ],
        image: DEFAULT_PROJECT_IMAGE,
        tools: ["Go", "PostgreSQL", "Redis", "ClickHouse", "Stripe", "bKash", "SSLCommerz"],
        stack: ["Go", "PostgreSQL", "Redis", "ClickHouse", "Stripe", "bKash", "SSLCommerz"],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "",
        links: { github: null, live: null },
    },
    {
        _id: "ph-skill-mapper",
        name: "Skill Mapper",
        title: "Skill Mapper",
        subtitle: "Technical Assessment Platform",
        time: "Production",
        shortDescription: "Technical assessment platform with state machine and leaderboards",
        metrics: ["5,000+ enrolled students", "500 daily active users", "5-tier XP ranking system"],
        priority: 93,
        category: "Full Stack / Product",
        status: "Production",
        tier: "featured",
        proprietary: false,
        caseStudyLink: "/projects/skill-mapper",
        description: [
            "Full-lifecycle technical assessment platform with an event state machine governing the assessment lifecycle (draft → published → active → completed → archived). Includes invite management, concurrent timed exams with real-time synchronization, and automated disqualification on rule violations.",
            "XP-based ranking engine with five tiers, per-assessment score caps, and a live leaderboard. The ranking design prevents score inflation from repeated assessments and handles tie-breaking fairly.",
            "Key engineering decisions: chose a state machine over status flags to prevent invalid transitions; used MongoDB change streams for real-time sync instead of polling; designed the leaderboard as a materialized view to avoid expensive aggregation queries on each request.",
        ],
        highlights: [
            "Event state machine with full lifecycle management",
            "Concurrent timed exams with real-time sync",
            "XP gamification with 5 rank tiers",
        ],
        image: SKILL_MAPPER_IMAGE,
        tools: [
            "TypeScript",
            "Node.js",
            "MongoDB",
            "Next.js",
            "TanStack Query",
            "shadcn/ui",
            "Tailwind CSS",
        ],
        stack: [
            "TypeScript",
            "Node.js",
            "MongoDB",
            "Next.js",
            "TanStack Query",
            "shadcn/ui",
            "Tailwind CSS",
        ],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "https://skillmapper.programming-hero.com",
        links: {
            github: null,
            live: "https://skillmapper.programming-hero.com",
        },
    },
    {
        _id: "ai-game-platform",
        name: "AI Game Platform",
        title: "AI Game Platform",
        subtitle: "AI-Powered Gamified Learning Platform",
        time: "MVP",
        shortDescription:
            "19-engine gamified micro-learning platform with AI-generated content, universal envelope architecture, and server-authoritative scoring (hackathon MVP)",
        metrics: [
            "19 game engines, 6-seam extensible registry",
            "Multi-provider AI pipeline (Anthropic, OpenAI, Gemini, OpenRouter)",
            "Server-authoritative scoring with Zod schema validation at both ends",
        ],
        priority: 91,
        category: "Full Stack / AI",
        status: "MVP",
        tier: "featured",
        proprietary: false,
        caseStudyLink: "/projects/ai-game-platform",
        description: [
            "Gamified micro-learning platform where students learn technical topics (web dev, DSA, programming) by playing interactive games instead of reading docs or watching videos. AI generates structured JSON content per game engine  the app never receives JSX, HTML, or React from the model. Content is validated by per-engine Zod schemas at both seed time and render time, eliminating the 'wrong-shape JSON to broken game' failure mode.",
            "Architecture is a pnpm monorepo with a shared @eduplay/schemas contract package consumed by both Express backend and React frontend. A universal envelope lifts cross-cutting concerns (XP, levels, rewards, timers, i18n, a11y, assets) out of individual engines into one forward-compatible wrapper. 19 game engines ship as frozen React templates  adding a new game is data plus one registry line, never a rewrite.",
            "AI content pipeline supports 4 providers (Anthropic, OpenAI, Gemini, OpenRouter) with a validated-retry loop: the model outputs inner content for one engine, Zod validates it, and on failure the system re-prompts with the validation errors until the shape is correct. All content is pre-seeded offline to MongoDB  the app runs fully without any LLM at runtime, proven by killing the API key during a live test.",
        ],
        highlights: [
            "Data-driven engine registry: 19 games, frozen React templates, JSON-driven rendering",
            "Universal envelope architecture  i18n, a11y, XP, timers added once for all engines",
            "Zod schemas as single source of truth, shared between backend and frontend",
            "Server-authoritative scoring  client submits raw results, server derives correctness",
            "Multi-provider AI pipeline with validated-retry and offline-first reliability",
        ],
        image: "/projects/ai-game-platform.webp",
        tools: [
            "TypeScript",
            "React",
            "Vite",
            "Tailwind CSS",
            "Express",
            "MongoDB",
            "Redis",
            "Anthropic",
            "Turborepo",
            "Docker",
        ],
        stack: [
            "TypeScript",
            "React",
            "Vite",
            "Tailwind CSS",
            "Express",
            "MongoDB",
            "Redis",
            "Anthropic",
            "Turborepo",
            "Docker",
        ],
        githubFrontEnd: "",
        githubBackEnd: "https://github.com/samiulalimsaad/hackathon-team-undefined-eduplay",
        live: "",
        links: {
            github: "https://github.com/samiulalimsaad/hackathon-team-undefined-eduplay",
            live: null,
        },
    },
];
