const DEFAULT_PROJECT_IMAGE = "/projects/default-project.svg";

export const projects = [
    {
        _id: "featured-1",
        name: "PH Mailer",
        title: "PH Mailer",
        subtitle: "Centralized Email Platform",
        time: "Production",
        shortDescription:
            "Production email platform replacing Mailgun at scale",
        priority: 105,
        category: "Backend / Platform",
        status: "Production",
        tier: "featured",
        proprietary: true,
        caseStudyLink: "/projects/ph-mailer",
        description: [
            "Centralized email platform built on Plunk to replace Mailgun costs across multiple product teams. The challenge was designing a shared service that multiple internal products could adopt without each team losing control over their email templates and delivery tracking.",
            "Own production maintenance, feature development, and upstream synchronization with Plunk's API. Responsibilities include delivery monitoring, bounce handling, and coordinating template changes across teams with different release schedules.",
            "Plunk was chosen over self-hosted SMTP (Postfix) and Amazon SES for its operational simplicity and built-in analytics. SES was rejected due to sandbox complexity and template management overhead for a small team.",
        ],
        highlights: [
            "Production platform ownership maintenance, monitoring, features",
            "Plunk-based centralized email replacing Mailgun at scale",
            "Cross-team coordination for shared internal service",
        ],
        image: DEFAULT_PROJECT_IMAGE,
        tools: ["Node.js", "TypeScript", "Plunk", "Docker"],
        stack: ["Node.js", "TypeScript", "Plunk", "Docker"],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "",
        links: { github: null, live: null },
    },
    {
        _id: "featured-2",
        title: "ph-auth-service",
        name: "PH Auth Service",
        subtitle: "Multi-Tenant Auth Platform",
        time: "2024 – Present",
        shortDescription:
            "Multi-tenant auth platform on ZITADEL with custom Go product layer",
        priority: 104,
        category: "Backend / Security",
        status: "Complete awaiting production release",
        tier: "featured",
        proprietary: true,
        caseStudyLink: "/projects/ph-auth-service",
        description: [
            "Multi-tenant authentication platform using ZITADEL as the OIDC provider, with a custom Go product layer handling tenant-specific business logic. ZITADEL was chosen over Keycloak (operational complexity for a small team) and Auth0 (cost at multi-tenant scale) for its OIDC compliance and self-hosting flexibility.",
            "The custom Go layer handles SSR UI rendering, per-tenant configuration, and security controls that ZITADEL doesn't expose through its OIDC interface: MFA enrollment flows, per-user device-limit enforcement, CSP nonce injection, rate limiting, ReCAPTCHA integration, and CSRF protection.",
            "Coordinated implementation and reviewed work for two mid-level engineers. Collaborative architecture decisions under Senior SWE authority; I owned the Go layer design and integration logic.",
        ],
        highlights: [
            "Hybrid auth: ZITADEL OIDC + custom Go product layer",
            "MFA, device limits, rate limiting, CSP, CSRF hardening",
            "Coordinated two engineers; collaborative architecture",
        ],
        image: DEFAULT_PROJECT_IMAGE,
        tools: ["Go", "PostgreSQL", "ZITADEL", "OIDC", "OAuth2"],
        stack: ["Go", "PostgreSQL", "ZITADEL", "OIDC", "OAuth2"],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "",
        links: { github: null, live: null },
    },
    {
        _id: "featured-3",
        name: "PH Bootcamp Platform",
        title: "PH Bootcamp Platform",
        subtitle: "Lead-Gen Education Platform",
        time: "Production",
        shortDescription:
            "Production education platform maintenance and feature development",
        priority: 103,
        category: "Backend / Platform",
        status: "Production",
        tier: "featured",
        proprietary: false,
        description: [
            "Production education platform where students access free courses, enroll, and submit information for business lead generation. Handles concurrent enrollment spikes during marketing campaigns and promotional events.",
            "Day-to-day production maintenance, new feature implementation, and cross-team coordination. Key responsibilities include monitoring enrollment pipelines, debugging production issues, and coordinating deployments with marketing schedules.",
        ],
        highlights: [
            "Production platform maintenance and feature development",
            "Cross-team coordination on shared education platform",
        ],
        image: DEFAULT_PROJECT_IMAGE,
        tools: ["Node.js", "TypeScript", "MongoDB", "Docker"],
        stack: ["Node.js", "TypeScript", "MongoDB", "Docker"],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "https://bootcamp.programming-hero.com",
        links: { github: null, live: "https://bootcamp.programming-hero.com" },
    },
    {
        _id: "past-1",
        name: "Enlightall",
        title: "Enlightall",
        subtitle: "Education Marketplace",
        time: "Independent",
        shortDescription:
            "Multi-role education marketplace with payments and real-time messaging",
        priority: 102,
        category: "Full Stack / Product",
        status: "Production",
        tier: "past-work",
        proprietary: false,
        description: [
            "Multi-role education marketplace covering course creation, lesson delivery, scheduling, quizzes, enrollment management, and instructor payment processing. The main challenge was designing a data model that supports four distinct user roles (admin, instructor, student, parent) with different permission scopes.",
            "Stripe Checkout integration with automated enrollment triggers. Socket.IO real-time messaging between instructors and students. Firebase Auth with Google OAuth for social login, JWT with httpOnly cookies for session management, and RBAC for access control.",
            "Domain expired after the project was completed. Code and architecture available on request.",
        ],
        highlights: [
            "Stripe Checkout with automated enrollment triggers",
            "Socket.IO real-time messaging",
            "Multi-role marketplace with RBAC",
        ],
        image: DEFAULT_PROJECT_IMAGE,
        tools: [
            "Next.js",
            "TypeScript",
            "Node.js",
            "MongoDB",
            "Socket.IO",
            "Stripe",
            "Firebase",
        ],
        stack: [
            "Next.js",
            "TypeScript",
            "Node.js",
            "MongoDB",
            "Socket.IO",
            "Stripe",
            "Firebase",
        ],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "",
        links: { github: null, live: null },
    },
    {
        _id: "past-2",
        name: "SpeakSail",
        title: "SpeakSail",
        subtitle: "Language Learning Marketplace",
        time: "Independent",
        shortDescription:
            "Language-learning instructor marketplace with RBAC and CMS",
        priority: 101,
        category: "Full Stack / Marketplace",
        status: "Production",
        tier: "past-work",
        proprietary: false,
        description: [
            "Laravel-based language-learning marketplace with multi-step instructor onboarding, availability matching, and a CMS with draft/published content lifecycle. The onboarding flow handles document verification, profile completion, and admin approval as separate state transitions.",
            "Policy-driven RBAC via Filament Shield and Spatie Permission. Moderation tools for instructor approval, blog, FAQ, and announcement workflows. SEO-friendly publishing with automatic sitemap generation.",
        ],
        highlights: [
            "Multi-step instructor onboarding and availability matching",
            "RBAC via Filament Shield and Spatie Permission",
            "CMS with draft/published lifecycle and moderation",
        ],
        image: DEFAULT_PROJECT_IMAGE,
        tools: [
            "Laravel 11",
            "PHP",
            "React",
            "TypeScript",
            "Inertia.js",
            "Filament",
            "MySQL",
            "Tailwind CSS",
        ],
        stack: [
            "Laravel 11",
            "PHP",
            "React",
            "TypeScript",
            "Inertia.js",
            "Filament",
            "MySQL",
            "Tailwind CSS",
        ],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "https://speaksail.com",
        links: { github: null, live: "https://speaksail.com" },
    },
    {
        _id: "past-3",
        name: "AI Game Platform",
        title: "AI Game Platform",
        subtitle: "Interactive Educational Gaming Platform",
        time: "Production",
        shortDescription:
            "Learning platform with interactive educational games for different age groups",
        priority: 100,
        category: "Full Stack / Product",
        status: "Production",
        tier: "past-work",
        proprietary: false,
        description: [
            "Designed the overall architecture, led technical implementation, developed the backend, and coordinated a team of three engineers from design through production deployment.",
            "Backend-driven game logic engine where game rules, scoring, and content are managed server-side and rendered by thin clients. This enables content updates and new game types without client releases, critical for an educational platform serving different age groups with varying difficulty levels.",
            "Key architectural decisions: game state machine for session management, content versioning for age-group-specific difficulty curves, and a game template system that allows non-technical content creators to configure new games.",
        ],
        highlights: [
            "Led architecture, backend, and team of 3 engineers end-to-end",
            "Designed and deployed from design through production",
        ],
        image: DEFAULT_PROJECT_IMAGE,
        tools: ["Node.js", "TypeScript", "MongoDB", "Docker"],
        stack: ["Node.js", "TypeScript", "MongoDB", "Docker"],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "https://eduplay.helloanwar.com",
        links: { github: null, live: "https://eduplay.helloanwar.com" },
    },
    {
        _id: "ph-drm-player",
        name: "Desktop DRM Player",
        title: "Desktop DRM Player",
        subtitle: "DRM-Protected Video Desktop App",
        time: "Production",
        shortDescription:
            "Electron desktop app for DRM-protected educational video playback",
        priority: 95,
        category: "Desktop / Security",
        status: "Production",
        tier: "past-work",
        proprietary: true,
        description: [
            "Electron desktop application for DRM-protected educational video playback. The core engineering challenge was implementing Widevine DRM within Electron's Chromium shell while supporting offline license caching for intermittent connectivity.",
            "Hit a hard constraint: upstream Chromium changes made fully offline DRM playback impossible — license validation now requires network communication. This changed the product's offline support model and required redesigning the playback flow to handle graceful degradation when connectivity drops mid-session.",
            "Led architecture, UI design, and implementation. Key decisions: license caching strategy, video player component selection, and handling DRM session lifecycle across app restarts.",
        ],
        highlights: [
            "Led architecture and implementation end-to-end",
            "DRM-protected video playback in Electron",
        ],
        image: DEFAULT_PROJECT_IMAGE,
        tools: ["Electron", "TypeScript", "DRM"],
        stack: ["Electron", "TypeScript", "DRM"],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "",
        links: { github: null, live: null },
    },
    {
        _id: "ph-payment-service",
        name: "Payment Service",
        title: "Payment Service",
        subtitle: "Centralized Payment Platform",
        time: "2024 – Present",
        shortDescription:
            "Centralized multi-gateway payment service for education products",
        priority: 94,
        category: "Backend / Payments",
        status: "In development",
        tier: "featured",
        proprietary: true,
        caseStudyLink: "/projects/payment-service",
        description: [
            "Centralized payment service abstracting multiple payment gateways behind a unified API with an adapter pattern. Supports Stripe, bKash, and SSLCommerz with webhook processing, refund management, and transaction analytics.",
            "Built with OpenAPI specification and Go code generation for type-safe API contracts. Uses PostgreSQL for transaction records, a columnar database for analytics queries, and Redis for gateway token caching.",
        ],
        highlights: [
            "Multi-gateway adapter pattern for payment abstraction",
            "OpenAPI-generated server with type-safe contracts",
            "Polyglot persistence for transaction, analytics, and cache",
        ],
        image: DEFAULT_PROJECT_IMAGE,
        tools: [
            "Go",
            "PostgreSQL",
            "Redis",
            "ClickHouse",
            "Stripe",
            "bKash",
            "SSLCommerz",
        ],
        stack: [
            "Go",
            "PostgreSQL",
            "Redis",
            "ClickHouse",
            "Stripe",
            "bKash",
            "SSLCommerz",
        ],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "",
        links: { github: null, live: null },
    },
    {
        _id: "ph-skill-mapper",
        name: "Skill Mapper",
        title: "Skill Mapper",
        subtitle: "Technical Assessment Platform",
        time: "Production",
        shortDescription:
            "Technical assessment platform with state machine and leaderboards",
        priority: 93,
        category: "Full Stack / Product",
        status: "Production",
        tier: "featured",
        proprietary: false,
        caseStudyLink: "/projects/skill-mapper",
        description: [
            "Full-lifecycle technical assessment platform with an event state machine governing the assessment lifecycle (draft → published → active → completed → archived). Includes invite management, concurrent timed exams with real-time synchronization, and automated disqualification on rule violations.",
            "XP-based ranking engine with five tiers, per-assessment score caps, and a live leaderboard. The ranking design prevents score inflation from repeated assessments and handles tie-breaking fairly.",
            "Key engineering decisions: chose a state machine over status flags to prevent invalid transitions; used MongoDB change streams for real-time sync instead of polling; designed the leaderboard as a materialized view to avoid expensive aggregation queries on each request.",
        ],
        highlights: [
            "Event state machine with full lifecycle management",
            "Concurrent timed exams with real-time sync",
            "XP gamification with 5 rank tiers",
        ],
        image: DEFAULT_PROJECT_IMAGE,
        tools: [
            "TypeScript",
            "Node.js",
            "MongoDB",
            "Next.js",
            "TanStack Query",
            "shadcn/ui",
            "Tailwind CSS",
        ],
        stack: [
            "TypeScript",
            "Node.js",
            "MongoDB",
            "Next.js",
            "TanStack Query",
            "shadcn/ui",
            "Tailwind CSS",
        ],
        githubFrontEnd: "",
        githubBackEnd: "",
        live: "https://skillmapper.programming-hero.com",
        links: { github: null, live: null },
    },
    {
        _id: "62e3ce709ab2aa1db3f07f2e",
        name: "Padma Convention Center",
        time: "(February 22)",
        shortDescription: "Convention center booking app built with React",
        priority: 92,
        tier: "learning",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/Padma-Convention-Hall.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd: "https://github.com/samiulalimsaad/convention-center",
        githubBackEnd: "",
        live: "https://convention-center-samiulalimsaad.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f26",
        name: "Lite Media",
        time: "(January 22)",
        shortDescription: "Social media-style app with Next.js and Firebase",
        priority: 100,
        tier: "learning",
        description: [
            "Nextjs with typescript",
            "Context-API",
            "Mongoose ORM for MongoDB",
            "Firebase for storing images, authentication, and real-time database, FireStore",
            "Python with Docker",
        ],
        image: "/sites/Lite-Media.png",
        tools: [
            "Nextjs",
            "typescript",
            "Context-API",
            "Mongoose ORM",
            "Firebase Authentication",
            "MongoDB",
            "Firebase",
            "FireStore",
            "Firebase Database",
            "Python",
            "Docker",
            "Docker-Compose",
            "TailwindCSS",
        ],
        githubFrontEnd: "https://github.com/samiulalimsaad/final-project",
        githubBackEnd: "https://github.com/samiulalimsaad/final-project",
        live: "https://light-media.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f27",
        name: "EC-360",
        time: "(May 22)",
        shortDescription: "E-commerce platform with Stripe payment integration",
        priority: 99,
        tier: "learning",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM, MongoDB with ExpressJS",
            "Stripe for payment",
        ],
        image: "/sites/Home-EC-360.png",
        tools: ["React.JS", "HTML", "CSS", "daisyui", "TailwindCSS"],
        githubFrontEnd: "https://github.com/samiulalimsaad/ec-360",
        githubBackEnd: "https://github.com/samiulalimsaad/ec-360-backend",
        live: "https://ec-360.web.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f2a",
        name: "Service-Provider",
        time: "(May 22)",
        shortDescription: "Service provider directory and booking platform",
        priority: 96,
        tier: "learning",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/John-Smith.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd: "https://github.com/samiulalimsaad/service-provider",
        githubBackEnd: "",
        live: "https://ph-assignment-10-d8306.web.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f36",
        name: "ISS Tracker",
        time: "(2021)",
        shortDescription: "International Space Station Tracker",
        priority: 70,
        tier: "learning",
        description: ["Html", "CSS", "JavaScript"],
        image: "/projects/ISS-Tracker.png",
        tools: ["Html", "CSS", "JavaScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/IssTracker",
        githubBackEnd: "",
        live: "https://iss-tracker-one.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f28",
        name: "Todo App (React)",
        time: "(May 22)",
        shortDescription: "Full-stack todo app with React and Express",
        priority: 98,
        tier: "learning",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM, MongoDB with ExpressJS",
            "Stripe for payment",
        ],
        image: "/sites/Home-Toto-App.png",
        tools: [
            "React.JS",
            "daisyui",
            "ExpressJS",
            "JavaScript",
            "TailwindCSS",
        ],
        githubFrontEnd: "https://github.com/samiulalimsaad/todo-app-react",
        githubBackEnd: "https://github.com/samiulalimsaad/todo-app-backend",
        live: "https://todo-app-react-taupe.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f2c",
        name: "Phone-Shope",
        time: "(April 22)",
        shortDescription: "Phone store e-commerce frontend",
        priority: 94,
        tier: "learning",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/Phone-Shop.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd: "https://github.com/samiulalimsaad/phone-shop-react",
        githubBackEnd: "",
        live: "https://phone-shop-react-samiulalimsaad.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f29",
        name: "SmartPhone-Warehouse",
        time: "(May 22)",
        shortDescription: "Smartphone warehouse inventory management app",
        priority: 97,
        tier: "learning",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/Home-Smartphone-Warehouse.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd:
            "https://github.com/samiulalimsaad/smartphone-warehouse",
        githubBackEnd:
            "https://github.com/samiulalimsaad/smartphone-warehouse-backend",
        live: "https://smartphone-warehouse-saad.web.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f2b",
        name: "Watch-Store",
        time: "(May 22)",
        shortDescription: "Watch store e-commerce platform",
        priority: 95,
        tier: "learning",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/Watch-Store.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd: "https://github.com/samiulalimsaad/watch-store",
        githubBackEnd: "",
        live: "https://watch-store-samiulalimsaad.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f30",
        name: "Mission",
        time: "(January 22)",
        shortDescription: "Mission planning and management app",
        priority: 89,
        tier: "learning",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/Mission.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd: "https://github.com/samiulalimsaad/mission",
        githubBackEnd: "",
        live: "https://mission-samiulalimsaad.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f34",
        name: "Todo App",
        time: "(2021)",
        shortDescription: "A web app for manage todo",
        priority: 80,
        tier: "learning",
        description: [
            "NextJS",
            "MaterialUI",
            "Firebase Database",
            "TypeScript",
        ],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2Fscreenshot-todo-azure-pi.vercel.app-2021.04.28-16_31_02.png?alt=media&token=5486342d-0a55-4e62-b09e-aa0e283e3be1",
        tools: ["Next.JS", "MaterialUI", "Firebase Database", "TypeScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/Todo",
        githubBackEnd: "",
        live: "https://todo-saadraj.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f37",
        name: "Password Generator",
        time: "(2021)",
        shortDescription: "Password Generator App",
        priority: 77,
        tier: "learning",
        description: ["NextJS", "MaterialUI", "JavaScript"],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2Fscreenshot-password-generator-jade-sigma.vercel.app-2021.04.28-16_37_58.png?alt=media&token=a647e153-7a2d-4124-968b-da71cde0247d",
        tools: ["Next.JS", "MaterialUI", "JavaScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/password-generator",
        githubBackEnd: "",
        live: "https://password-generator-jade-sigma.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f2d",
        name: "Dollar-Bank",
        time: "(March 22)",
        shortDescription: "Dollar bank finance tracking application",
        priority: 93,
        tier: "learning",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/Dollar-Bank.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd: "https://github.com/samiulalimsaad/money-master",
        githubBackEnd: "",
        live: "https://money-master-samiulalimsaad.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f31",
        name: "Real Time Chatting Application",
        time: "(2021)",
        shortDescription: "Application for chatting real time.",
        priority: 88,
        tier: "learning",
        description: [
            "NextJS",
            "MaterialUI",
            "Firebase Realtime Database",
            "TypeScript",
        ],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2Fscreenshot-real-time-chatting-saadraj.vercel.app-2021.05.02-22_58_24.png?alt=media&token=f07ff458-6baa-45ad-ab59-ebeaded7f161",
        tools: ["Next.JS", "MaterialUI", "Firebase Database", "TypeScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/realTimeChatting",
        githubBackEnd: "",
        live: "https://real-time-chatting-saadraj.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f32",
        name: "URL Shortener",
        time: "(2021)",
        shortDescription: "Application for URL shortener",
        priority: 70,
        tier: "learning",
        description: [
            "NextJS",
            "MaterialUI",
            "Firebase Database",
            "TypeScript",
        ],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2FURL-Shortener.png?alt=media&token=60bd2e81-9655-4aea-8421-5b54fa180a58",
        tools: ["Next.JS", "MaterialUI", "Firebase Database", "TypeScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/urlShortener",
        githubBackEnd: "",
        live: "https://url-shortener-saadraj.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f33",
        name: "Tic Tac Toe",
        time: "(2021)",
        shortDescription: "Tic Tac Toe game",
        priority: 90,
        tier: "learning",
        description: [
            "NextJS",
            "MaterialUI",
            "Firebase Database",
            "TypeScript",
        ],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2Fscreenshot-tic-tac-toe-rust.vercel.app-2021.04.28-16_33_02.png?alt=media&token=62d02698-0825-4090-b4b0-6719a031bd3c",
        tools: ["Next.JS", "MaterialUI", "Firebase Database", "TypeScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/tic-tac-toe",
        githubBackEnd: "",
        live: "https://tic-tac-toe-rust.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f38",
        name: "Weather App",
        time: "(2021)",
        shortDescription: "A simple weather for broadcast current weather",
        priority: 77,
        tier: "learning",
        description: ["NextJS", "MaterialUI", "TypeScript"],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2Fscreenshot-weather-plum.vercel.app-2021.04.28-16_34_32.png?alt=media&token=d4626788-6391-4b24-b27e-da9e36f6aea4",
        tools: ["Next.JS", "MaterialUI", "TypeScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/weather",
        githubBackEnd: "",
        live: "https://weather-saadraj.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f39",
        name: "Color Generator",
        time: "(2021)",
        shortDescription: "RGBA color generator",
        priority: 77,
        tier: "learning",
        description: ["NextJS", "MaterialUI", "TypeScript"],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2Flocalhost-3000.png?alt=media&token=b2a35908-c435-406e-86a1-9e32d826f2b0",
        tools: ["Next.JS", "MaterialUI", "TypeScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/weather",
        githubBackEnd: "",
        live: "https://color-generator-saadraj.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f2f",
        name: "Influencer Gear | TailwindCSS",
        time: "(February 22)",
        shortDescription: "Influencer gear landing page with Tailwind CSS",
        priority: 91,
        tier: "learning",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/Influencer-Gear-Tailwind.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd:
            "https://github.com/samiulalimsaad/Influencer-gear-tailwind",
        githubBackEnd: "",
        live: "https://vercel.com/samiulalimsaad/influencer-gear-tailwind",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f35",
        name: "Shopper",
        time: "(2021)",
        shortDescription: "An e-commerce app with limited features",
        priority: 70,
        tier: "learning",
        description: [
            "NextJS",
            "MaterialUI",
            "Firebase Database",
            "TypeScript",
        ],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2FShopper-web-store.png?alt=media&token=f4fc584a-d241-4478-adb5-0e4dec5efec9",
        tools: ["Next.JS", "MaterialUI", "Firebase Database", "TypeScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/Todo",
        githubBackEnd: "",
        live: "https://shopper-saadraj.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f3a",
        name: "Drag and Drop",
        time: "(June 2022)",
        shortDescription: "Equation solver game with Drag and Drop",
        priority: 91,
        tier: "learning",
        description: [
            "NextJS",
            "daisyui",
            "tailwindCSS",
            "TypeScript",
            "ExpressJS",
        ],
        image: "/sites/Drag-and-Drop.png",
        tools: ["NextJS", "daisyui", "tailwindCSS", "TypeScript", "ExpressJS"],
        githubFrontEnd: "https://github.com/samiulalimsaad/react-drag-and-drop",
        githubBackEnd: "",
        live: "https://react-drag-and-drop-samiulalimsaad.vercel.app",
    },
    {
        _id: "62e3ce709ab2aa1db3f07f3b",
        name: "Web Amboos Traffic Permit",
        time: "(June 2022)",
        shortDescription: "Traffic management landing page",
        priority: 91,
        tier: "learning",
        description: [
            "ReactJS",
            "daisyui",
            "tailwindCSS",
            "TypeScript",
            "ExpressJS",
        ],
        image: "/sites/Web-Amboos.png",
        tools: ["NextJS", "daisyui", "tailwindCSS", "TypeScript", "ExpressJS"],
        githubFrontEnd: "https://github.com/samiulalimsaad/web-amboos-react",
        githubBackEnd: "https://github.com/samiulalimsaad/webamboos-node",
        live: "https://web-amboos-react-samiulalimsaad.vercel.app",
    },
    {
        _id: "63086203e9cb9de5827108d2",
        name: "Blog filter (Redux)",
        time: "(2022)",
        shortDescription: "Blog filter app using Redux",
        priority: 87,
        tier: "learning",
        description: ["React", "Redux", "JavaScript", "TailwindCSS"],
        image: "/sites/Blog-Home.png",
        tools: ["React", "Redux", "JavaScript", "TailwindCSS", "React-Redux"],
        githubFrontEnd: "https://github.com/samiulalimsaad/blog-react-redux",
        githubBackEnd: "",
        live: "https://blog-react-redux-samiulalimsaad.vercel.app",
    },
    {
        _id: "63086203e9cb9de5827108d0",
        name: "Multi Counter App (Vanilla Redux)",
        time: "(2022)",
        shortDescription: "multi counter app using vanilla Redux",
        priority: 87,
        tier: "learning",
        description: ["HTML", "Redux", "JavaScript", "TailwindCSS"],
        image: "/sites/Multi-Counter-App.png",
        tools: ["HTML", "Redux", "JavaScript", "TailwindCSS"],
        githubFrontEnd:
            "https://github.com/samiulalimsaad/multi-counter-application-vanilla-redux",
        githubBackEnd: "",
        live: "https://multi-counter-application-vanilla-redux-samiulalimsaad.vercel.app",
    },
    {
        _id: "63086203e9cb9de5827108d1",
        name: "Shopping Cart App (Redux)",
        time: "(2022)",
        shortDescription: "Shopping Cart app using Redux",
        priority: 87,
        tier: "learning",
        description: ["React", "Redux", "JavaScript", "TailwindCSS"],
        image: "/sites/Shopping-Cart-with-React-Redux.png",
        tools: ["React", "Redux", "JavaScript", "TailwindCSS", "React-Redux"],
        githubFrontEnd:
            "https://github.com/samiulalimsaad/shopping-cart-application-react-redux",
        githubBackEnd: "",
        live: "https://shopping-cart-application-react-redux-samiulalimsaad.vercel.app",
    },
];
