export type SkillGroup = {
    category: string;
    items: string[];
};

export const skills: SkillGroup[] = [
    {
        category: "Languages",
        items: [
            "TypeScript",
            "JavaScript",
            "Go",
            "Python",
            "PHP",
            "SQL",
            "C",
            "C++",
            "Dart",
            "Markdown",
        ],
    },
    {
        category: "Backend",
        items: [
            "Node.js",
            "Express.js",
            "Go",
            "Laravel",
            "PHP",
            "Django",
            "Flask",
            "FastAPI",
            "NestJS",
            "Symfony",
            "Socket.IO",
            "REST API Design",
            "GraphQL",
            "OpenAPI",
            "Bull/Queue",
            "Mongoose",
            "Prisma ORM",
            "Redis",
            "Zod",
        ],
    },
    {
        category: "Databases",
        items: [
            "PostgreSQL",
            "MongoDB",
            "MySQL",
            "SQLite",
            "Firebase",
        ],
    },
    {
        category: "Security & Identity",
        items: [
            "OIDC",
            "OAuth2",
            "JWT",
            "ABAC",
            "RBAC",
            "Firebase Auth",
            "Google OAuth",
            "CSP",
            "ReCAPTCHA v2/v3",
            "Rate Limiting",
            "Spatie Permission",
        ],
    },
    {
        category: "DevOps & Cloud",
        items: [
            "Docker",
            "GitHub Actions",
            "release-please",
            "Biome",
            "Cloudflare Pages",
            "AWS S3",
            "Nginx",
            "PM2",
            "Vercel",
            "Git",
            "GitHub",
            "Debian",
            "Ubuntu",
            "Linux",
            "Bash",
            "npm",
            "Yarn",
        ],
    },
    {
        category: "Frontend",
        items: [
            "React.js",
            "Next.js",
            "Vue.js",
            "Nuxt.js",
            "SSR",
            "MERN",
            "Redux Toolkit",
            "Zustand",
            "RTK Query",
            "React Query",
            "Tailwind CSS",
            "Material UI",
            "Bootstrap",
            "HTML5",
            "CSS3",
            "Flutter",
            "Ionic",
            "Electron",
            "Apollo GraphQL",
        ],
    },
    {
        category: "Analytics",
        items: [
            "GTM (server-side)",
            "Meta Conversion API",
            "Meta Pixel",
            "Microsoft Clarity",
        ],
    },
    {
        category: "Testing",
        items: [
            "Vitest",
            "Jest",
            "React Testing Library",
            "API Integration Testing",
            "Postman",
            "ESLint",
        ],
    },
    {
        category: "Tools & Workflow",
        items: [
            "VS Code",
            "Figma",
            "Adobe XD",
            "Postman",
            "Trello",
            "Jira",
            "Jupyter",
            "Anaconda",
            "Arduino",
        ],
    },
];
