export const skills = [
    "React.JS",
    "Next.JS",
    "VueJS",
    "HTML",
    "CSS",
    "daisyui",
    "Redux",
    "JavaScript",
    "Typescript",
    "TailwindCSS",
    "Context-API",
    "Vuex",
    "Express.Js",
    "Firebase",
    "Python",
    "PHP",
    "Symfony",
    "Flask",
    "NoSQL",
    "SQL",
    "MongoDB",
    "FireStore",
    "Mongoose",
    "Doctrine",
    "Git",
    "GitHub",
    "Docker",
    "Sonata Admin",
    "Stripe",
    "Netlify",
    "Vercel",
    "Authorization",
    "Authentication",
    "Problem Solving",
    "GraphQL",
    "Bootstrap",
    "Material Design Bootstrap",
    "REST-API",
    "Material-UI",
    "node JS",
    "Logic Build",
    "JAVA",
    "C++",
    "C",
    "Artificial Intelligence",
    "Linux",
    "Deep Learning",
    "Strapi",
    "Neural Network",
    "Machine Learning",
];
