export const projects: projectInterface[] = [
    {
        name: "Lite Media",
        time: "(January 22)",
        shortDescription: "Python with Docker",
        description: [
            "Nextjs with typescript",
            "Context-API",
            "Mongoose ORM for MongoDB",
            "Firebase for storing images, authentication, and real-time database, FireStore",
            "Python with Docker",
        ],
        image: "/sites/Lite-Media.png",
        tools: [
            "Nextjs",
            "typescript",
            "Context-API",
            "Mongoose ORM",
            "Firebase Authentication",
            "MongoDB",
            "Firebase",
            "FireStore",
            "Firebase Database",
            "Python",
            "Docker",
            "Docker-Compose",
            "TailwindCSS",
        ],
        githubFrontEnd: "https://github.com/samiulalimsaad/final-project",
        githubBackEnd: "https://github.com/samiulalimsaad/final-project",
        live: "https://light-media.vercel.app",
    },
    {
        name: "EC-360",
        time: "(May 22)",
        shortDescription: "Python with Docker",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM, MongoDB with ExpressJS",
            "Stripe for payment",
        ],
        image: "/sites/Home-EC-360.png",
        tools: ["React.JS", "HTML", "CSS", "daisyui", "TailwindCSS"],
        githubFrontEnd: "https://github.com/samiulalimsaad/ec-360",
        githubBackEnd: "https://github.com/samiulalimsaad/ec-360-backend",
        live: "https://ec-360.web.app",
    },
    {
        name: "Todo App (React)",
        time: "(May 22)",
        shortDescription: "Python with Docker",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM, MongoDB with ExpressJS",
            "Stripe for payment",
        ],
        image: "/sites/Home-Toto-App.png",
        tools: [
            "React.JS",
            "daisyui",
            "ExpressJS",
            "JavaScript",
            "TailwindCSS",
        ],
        githubFrontEnd: "https://github.com/samiulalimsaad/todo-app-react",
        githubBackEnd: "https://github.com/samiulalimsaad/todo-app-backend",
        live: "https://todo-app-react-taupe.vercel.app",
    },
    {
        name: "SmartPhone-Warehouse",
        time: "(May 22)",
        shortDescription: "Python with Docker",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/Home-Smartphone-Warehouse.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd:
            "https://github.com/samiulalimsaad/smartphone-warehouse",
        githubBackEnd:
            "https://github.com/samiulalimsaad/smartphone-warehouse-backend",
        live: "https://smartphone-warehouse-saad.web.app",
    },
    {
        name: "Service-Provider",
        time: "(May 22)",
        shortDescription: "Python with Docker",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/John-Smith.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd: "https://github.com/samiulalimsaad/service-provider",
        githubBackEnd: "",
        live: "https://ph-assignment-10-d8306.web.app",
    },
    {
        name: "Watch-Store",
        time: "(May 22)",
        shortDescription: "Python with Docker",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/Watch-Store.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd: "https://github.com/samiulalimsaad/watch-store",
        githubBackEnd: "",
        live: "https://watch-store-samiulalimsaad.vercel.app",
    },
    {
        name: "Phone-Shope",
        time: "(April 22)",
        shortDescription: "Python with Docker",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/Phone-Shop.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd: "https://github.com/samiulalimsaad/phone-shop-react",
        githubBackEnd: "",
        live: "https://phone-shop-react-samiulalimsaad.vercel.app",
    },
    {
        name: "Dollar-Bank",
        time: "(March 22)",
        shortDescription: "Python with Docker",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/Dollar-Bank.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd: "https://github.com/samiulalimsaad/money-master",
        githubBackEnd: "",
        live: "https://money-master-samiulalimsaad.vercel.app",
    },
    {
        name: "Padma Convention Center",
        time: "(February 22)",
        shortDescription: "Python with Docker",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/Padma-Convention-Hall.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd: "https://github.com/samiulalimsaad/convention-center",
        githubBackEnd: "",
        live: "https://convention-center-samiulalimsaad.vercel.app",
    },
    {
        name: "Influencer Gear | TailwindCSS",
        time: "(February 22)",
        shortDescription: "Python with Docker",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/Influencer-Gear-Tailwind.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd:
            "https://github.com/samiulalimsaad/Influencer-gear-tailwind",
        githubBackEnd: "",
        live: "https://vercel.com/samiulalimsaad/influencer-gear-tailwind",
    },
    {
        name: "Mission",
        time: "(January 22)",
        shortDescription: "Python with Docker",
        description: [
            "ReactJS with React-Router-Dom",
            "daisyui, tailwindCSS",
            "Firebase authentication",
            "Mongoose ORM for MongoDB with ExpressJS",
        ],
        image: "/sites/Mission.png",
        tools: ["React.JS", "Next.JS", "VueJS", "HTML", "CSS", "daisyui"],
        githubFrontEnd: "https://github.com/samiulalimsaad/mission",
        githubBackEnd: "",
        live: "https://mission-samiulalimsaad.vercel.app",
    },
    {
        name: "Real Time Chatting Application",
        time: "(2021)",
        shortDescription: "Application for chatting real time.",
        description: [
            "NextJS",
            "MaterialUI",
            "Firebase Realtime Database",
            "TypeScript",
        ],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2Fscreenshot-real-time-chatting-saadraj.vercel.app-2021.05.02-22_58_24.png?alt=media&token=f07ff458-6baa-45ad-ab59-ebeaded7f161",
        tools: ["Next.JS", "MaterialUI", "Firebase Database", "TypeScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/realTimeChatting",
        githubBackEnd: "",
        live: "https://real-time-chatting-saadraj.vercel.app",
    },
    {
        name: "URL Shortener",
        time: "(2021)",
        shortDescription: "Application for URL shortener",
        description: [
            "NextJS",
            "MaterialUI",
            "Firebase Database",
            "TypeScript",
        ],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2FURL-Shortener.png?alt=media&token=60bd2e81-9655-4aea-8421-5b54fa180a58",
        tools: ["Next.JS", "MaterialUI", "Firebase Database", "TypeScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/urlShortener",
        githubBackEnd: "",
        live: "https://url-shortener-saadraj.vercel.app",
    },
    {
        name: "Tic Tac Toe",
        time: "(2021)",
        shortDescription: "Tic Tac Toe game",
        description: [
            "NextJS",
            "MaterialUI",
            "Firebase Database",
            "TypeScript",
        ],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2Fscreenshot-tic-tac-toe-rust.vercel.app-2021.04.28-16_33_02.png?alt=media&token=62d02698-0825-4090-b4b0-6719a031bd3c",
        tools: ["Next.JS", "MaterialUI", "Firebase Database", "TypeScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/tic-tac-toe",
        githubBackEnd: "",
        live: "https://tic-tac-toe-rust.vercel.app",
    },
    {
        name: "Todo App",
        time: "(2021)",
        shortDescription: "A web app for manage todo",
        description: [
            "NextJS",
            "MaterialUI",
            "Firebase Database",
            "TypeScript",
        ],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2Fscreenshot-todo-azure-pi.vercel.app-2021.04.28-16_31_02.png?alt=media&token=5486342d-0a55-4e62-b09e-aa0e283e3be1",
        tools: ["Next.JS", "MaterialUI", "Firebase Database", "TypeScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/Todo",
        githubBackEnd: "",
        live: "https://todo-saadraj.vercel.app",
    },
    {
        name: "Shopper",
        time: "(2021)",
        shortDescription: "An e-commerce app with limited features",
        description: [
            "NextJS",
            "MaterialUI",
            "Firebase Database",
            "TypeScript",
        ],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2FShopper-web-store.png?alt=media&token=f4fc584a-d241-4478-adb5-0e4dec5efec9",
        tools: ["Next.JS", "MaterialUI", "Firebase Database", "TypeScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/Todo",
        githubBackEnd: "",
        live: "https://shopper-saadraj.vercel.app",
    },
    {
        name: "ISS Tracker",
        time: "(2021)",
        shortDescription: "International Space Station Tracker",
        description: ["Html", "CSS", "JavaScript"],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2Fscreenshot-iss-tracker-one.vercel.app-2021.04.28-16_36_23.png?alt=media&token=45c441b1-d5bd-4fb1-b915-de459fbda2aa",
        tools: ["Html", "CSS", "JavaScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/IssTracker",
        githubBackEnd: "",
        live: "https://iss-tracker-one.vercel.app",
    },
    {
        name: "Password Generator",
        time: "(2021)",
        shortDescription: "Password Generator App",
        description: ["NextJS", "MaterialUI", "JavaScript"],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2Fscreenshot-password-generator-jade-sigma.vercel.app-2021.04.28-16_37_58.png?alt=media&token=a647e153-7a2d-4124-968b-da71cde0247d",
        tools: ["Next.JS", "MaterialUI", "JavaScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/password-generator",
        githubBackEnd: "",
        live: "https://password-generator-jade-sigma.vercel.app",
    },
    {
        name: "Weather App",
        time: "(2021)",
        shortDescription: "A simple weather for broadcast current weather",
        description: ["NextJS", "MaterialUI", "TypeScript"],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2Fscreenshot-weather-plum.vercel.app-2021.04.28-16_34_32.png?alt=media&token=d4626788-6391-4b24-b27e-da9e36f6aea4",
        tools: ["Next.JS", "MaterialUI", "TypeScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/weather",
        githubBackEnd: "",
        live: "https://weather-saadraj.vercel.app",
    },
    {
        name: "Color Generator",
        time: "(2021)",
        shortDescription: "RGBA color generator",
        description: ["NextJS", "MaterialUI", "TypeScript"],
        image: "https://firebasestorage.googleapis.com/v0/b/personal-website-2994f.appspot.com/o/portfolio%2Flocalhost-3000.png?alt=media&token=b2a35908-c435-406e-86a1-9e32d826f2b0",
        tools: ["Next.JS", "MaterialUI", "TypeScript"],
        githubFrontEnd: "https://github.com/samiulalimsaad/weather",
        githubBackEnd: "",
        live: "https://color-generator-saadraj.vercel.app",
    },
];

export interface projectInterface {
    shortDescription: string;
    name: string;
    time: string;
    description: string[];
    image: string;
    tools: string[];
    githubFrontEnd: string;
    githubBackEnd: string;
    live: string;
}
